project_name: kube-ingress-index
before:
  hooks:
    - go mod download
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "registry.banno-internal.com/{{.ProjectName}}:{{.Tag}}"
      - "registry.banno-internal.com/{{.ProjectName}}:{{.Major}}"
      - "registry.banno-internal.com/{{.ProjectName}}:{{.Major}}.{{.Minor}}"
      - "registry.banno-internal.com/{{.ProjectName}}:latest"
    build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=org.label-schema.vendor=Jack Henry & Associates"
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.name={{.ProjectName}}"
    - "--label=org.label-schema.vcs-url={{.GitURL}}"
release:
  github:
    owner: banno
    name: "{{.ProjectName}}"
  prerelease: auto
builds:
  - goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    flags:
      - -a
    ldflags:
      - -s
      - -w
archive:
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{.Tag}}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
